version: "3"
services:
  web:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - citadel-test
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - citadel-test
    environment:
      POSTGRES_USER: citadel
      POSTGRES_PASSWORD: citadel_test
      POSTGRES_DB: citadel
    volumes:
    - citadel-postgres:/var/lib/postgresql/data

volumes:
  citadel-postgres:
    external: false

networks:
  citadel-test:
    driver: bridge
