version: "3"
services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - taskcafe-test
    environment:
      POSTGRES_USER: taskcafe
      POSTGRES_PASSWORD: taskcafe_test
      POSTGRES_DB: taskcafe
    volumes:
      - taskcafe-postgres:/var/lib/postgresql/data
    ports:
      - 8865:5432
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
  redis:
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379

volumes:
  taskcafe-postgres:
    external: false

networks:
  taskcafe-test:
    driver: bridge
