blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/JordanKnott/taskcafe/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Ask a Question
    url: https://github.com/JordanKnott/taskcafe/discussions/new?category=q-a
    about: Ask the community for help
