[server]
hostname = '0.0.0.0:3333'

[email_notifications]
enabled = true
display_name = "No Reply"
from_address = "example.com"

[storage]
storage_system = 'local_storage'
upload_dir_path = 'uploads'

[database]
host = 'postgres'
name = 'taskcafe'
user = 'taskcafe'
password = 'taskcafe_test'

[smtp]
username = 'admin@example.com'
password = 'example'
server = 'mail.example.com'
port = 465
connection_security = 'STARTTLS'
